namespace HTS.BusinessException;
public static class  ErrorCode
{
    public const string StaffAlreadyExist = "HTS:1";
    public const string DefaultStaffAlreadyExist = "HTS:2";
    public const string NationalityAndPassportNumberMustBeUnique = "HTS:3";
    public const string CreatorCanRevokePatientNote = "HTS:4";
    public const string CreatorCanRevokePatientDocument = "HTS:5";
    public const string PtpStatusNotValidToHospitalConsultation = "HTS:6";
    public const string RelationalDataIsMissing = "HTS:7";
    public const string HospitalAlreadyResponsed = "HTS:8";
    public const string RequiredFieldsMissingForSuitableForTreatment = "HTS:9";
    public const string HospitalResponseTypeNotValidToApprove = "HTS:10";
    public const string HospitalResponseTypeNotValidToReject = "HTS:11";
    public const string AnotherHospitalResponseIsApprovedInSameRowNumber = "HTS:12";
    public const string TreatmentNumberCouldNotBeGenerated = "HTS:13";
    public const string NoExchangeRateInformation = "HTS:14";
    public const string ExchangeRateInformationNotMatch = "HTS:15";
    public const string ProformaStatusNotValid = "HTS:16";
    public const string ProformaAdditionalServiceNotValid = "HTS:17";
    public const string InvalidProcessInProforma = "HTS:18";
    public const string InvalidProcessUnitPriceInProforma = "HTS:19";
    public const string InvalidCalculationsInProforma = "HTS:20";
    public const string BadRequest = "HTS:20";
    public const string LastProformaVersionCanBeApprovedRejected = "HTS:21";
    public const string LastProformaVersionCanBeOperated = "HTS:22";
    public const string RequiredFieldsMissing = "HTS:23";
    public const string OperationStatusNotValid = "HTS:24";
    public const string NoPaymentDocumentUploaded = "HTS:25";
    public const string PaymentTotalAmountLessThanProformaAmount = "HTS:26";
    public const string ThereCanOnlyBeOneDocument = "HTS:27";
    public const string PricerAlreadyExist = "HTS:28";
    public const string DefaultPricerAlreadyExist = "HTS:29";
    public const string NoPaymentCompletedProforma = "HTS:32";
    public const string AlreadyAssignedToTik = "HTS:33";
    public const string NoAssignedUserToTickRole = "HTS:34";
    public const string PatinentNotSetAsAssignedToTik = "HTS:35";
    public const string NoUserInHospitalPricer = "HTS:36";
    public const string NoOperationWithoutProforma = "HTS:37";
    public const string CreatorCanRevokeHospitalAgentNote = "HTS:38";
    public const string CannotEditCompletedPayment = "HTS:39";
    public const string ThereIsNoHospitalOrApprovedProforma = "HTS:40";
}